# Generated by Django 4.2.5 on 2023-10-05 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thelist', '0002_alter_tasks_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='dateCompleted',
            field=models.DateField(help_text='When the task was completed.', null=True),
        ),
    ]
