# Generated by Django 4.2.5 on 2023-10-26 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thelist', '0003_alter_tasks_datecompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='dueDate',
            field=models.DateField(help_text='When is this task due', null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='priority',
            field=models.IntegerField(help_text='Priority Level', null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='tag',
            field=models.CharField(help_text='Category or label for this task', max_length=80, null=True),
        ),
    ]
