# Generated by Django 4.2.5 on 2023-10-26 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thelist', '0005_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='thelist.tags'),
        ),
    ]
